---@type table
local defaults = {
  client_filters = "first",
  renderers = {
    root = {
      { "indent" },
      { "kind_icon" },
      { "name", zindex = 10 },
    },
    directory = {
      { "indent", with_expanders = true },
      { "kind_icon" },
      {
        "container",
        content = {
          { "name", zindex = 10 },
          { "detail", zindex = 10, prefix = " ", highlight = "Function" },
        },
      },
    },
    message = {
      { "indent" },
      { "name", zindex = 10 },
    },
  },
  window = {
    mappings = {
      ["<cr>"] = "toggle_node",
      ["<2-LeftMouse>"] = "toggle_node",
      ["o"] = "jump_to_item",
      ["l"] = "toggle_node",
      ["h"] = "close_node",
      ["s"] = "noop",
      ["S"] = "noop",
      ["t"] = "noop",
      ["w"] = "noop",
      ["a"] = "noop",
      ["A"] = "noop",
      ["d"] = "noop",
      ["r"] = "noop",
      ["y"] = "noop",
      ["x"] = "noop",
      ["p"] = "noop",
      ["<C-r>"] = "noop",
      ["c"] = "noop",
      ["m"] = "noop",
      ["gd"] = "toggle_direction",
      ["/"] = "filter",
      ["f"] = "filter_on_submit",
    },
  },
  custom_kinds = {},
  kinds = {
    Unknown = { icon = "?", hl = "" },
    Root = { icon = "", hl = "NeoTreeRootName" },
    File = { icon = "󰈙", hl = "Tag" },
    Module = { icon = "", hl = "Exception" },
    Namespace = { icon = "󰌗", hl = "Include" },
    Package = { icon = "󰏖", hl = "Label" },
    Class = { icon = "󰌗", hl = "Include" },
    Method = { icon = "", hl = "Function" },
    Property = { icon = "󰆧", hl = "@property" },
    Field = { icon = "", hl = "@field" },
    Constructor = { icon = "", hl = "@constructor" },
    Enum = { icon = "󰒻", hl = "@number" },
    Interface = { icon = "", hl = "Type" },
    Function = { icon = "󰊕", hl = "Function" },
    Variable = { icon = "", hl = "@variable" },
    Constant = { icon = "", hl = "Constant" },
    String = { icon = "󰀬", hl = "String" },
    Number = { icon = "󰎠", hl = "Number" },
    Boolean = { icon = "", hl = "Boolean" },
    Array = { icon = "󰅪", hl = "Type" },
    Object = { icon = "󰅩", hl = "Type" },
    Key = { icon = "󰌋", hl = "" },
    Null = { icon = "", hl = "Constant" },
    EnumMember = { icon = "", hl = "Number" },
    Struct = { icon = "󰌗", hl = "Type" },
    Event = { icon = "", hl = "Constant" },
    Operator = { icon = "󰆕", hl = "Operator" },
    TypeParameter = { icon = "󰊄", hl = "Type" },
  },
}

return defaults
